#!/usr/bin/env bash

COUCH_URL="http://${COUCH_USER}:${COUCH_PASS}@localhost:5984"
NAME=$2
PASS=$3
ID=org.couchdb.user:$NAME

JSON='{ "_id": "'$ID'", "type": "user", "roles": ["mentor"], "name": "'$NAME'", "password": "'$PASS'" }'

curl \
  -H Content-Type:application/json \
  -X PUT \
  $COUCH_URL/_users/$ID \
  -d "$JSON"
